#!/usr/bin/env python3
"""Regenerate data/photos.json and photos/thumbs/ from whatever is in photos/.

Run automatically by .github/workflows/photos.yml whenever an image is added
to the photos/ folder. You can also run it locally:

    pip install pillow
    python scripts/build_photos.py

The gallery shows photos without captions.
"""
from __future__ import annotations

import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    from PIL import Image, ImageOps
except ImportError:  # pragma: no cover
    sys.exit("Pillow is required: pip install pillow")

ROOT = Path(__file__).resolve().parents[1]
PHOTOS = ROOT / "photos"
THUMBS = PHOTOS / "thumbs"
OUT = ROOT / "data" / "photos.json"
# The archived Harvard BJJ site has its own gallery, fed by alumni uploads
GALLERIES = [
    (PHOTOS, THUMBS, OUT, "photos"),
    (PHOTOS / "legacy", PHOTOS / "legacy" / "thumbs", ROOT / "data" / "legacy-photos.json", "photos/legacy"),
]
EXTS = {".jpg", ".jpeg", ".png", ".webp"}
THUMB_SIZE = 600      # px, longest side of the square-cropped thumbnail
FULL_MAX = 2000       # px, longest side; larger originals are downscaled in place


def main() -> None:
    for src, thumbs, out, prefix in GALLERIES:
        if src.exists():
            build(src, thumbs, out, prefix)


def build(PHOTOS: Path, THUMBS: Path, OUT: Path, PREFIX: str) -> None:
    THUMBS.mkdir(parents=True, exist_ok=True)
    files = sorted(
        (p for p in PHOTOS.iterdir() if p.is_file() and p.suffix.lower() in EXTS),
        key=lambda p: p.name.lower(),
    )
    photos = []
    for p in files:
        try:
            with Image.open(p) as im:
                im = ImageOps.exif_transpose(im)
                # Downscale huge phone photos in place so the site stays fast.
                if max(im.size) > FULL_MAX:
                    im.thumbnail((FULL_MAX, FULL_MAX))
                    save_kwargs = {"quality": 85, "optimize": True} if p.suffix.lower() in {".jpg", ".jpeg"} else {}
                    im.save(p, **save_kwargs)
                w, h = im.size
                thumb = ImageOps.fit(im.convert("RGB"), (THUMB_SIZE, THUMB_SIZE), method=Image.LANCZOS)
                tpath = THUMBS / (p.stem + ".jpg")
                thumb.save(tpath, "JPEG", quality=80, optimize=True, progressive=True)
        except Exception as e:  # skip anything Pillow can't read
            print(f"skip {p.name}: {e}", file=sys.stderr)
            continue
        photos.append({
            "full": f"{PREFIX}/{p.name}",
            "thumb": f"{PREFIX}/thumbs/{tpath.name}",
            "w": w, "h": h,
        })

    # Remove orphaned thumbnails
    keep = {Path(ph["thumb"]).name for ph in photos}
    for t in THUMBS.glob("*.jpg"):
        if t.name not in keep:
            t.unlink()

    # Only rewrite if the photo list actually changed (avoids no-op commits)
    try:
        previous = json.loads(OUT.read_text(encoding="utf-8")).get("photos")
    except Exception:
        previous = None
    if previous == photos:
        print(f"{len(photos)} photos, unchanged")
        return
    OUT.write_text(json.dumps({
        "_help": "Generated by scripts/build_photos.py via GitHub Actions. Do not edit by hand.",
        "generated": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "photos": photos,
    }, indent=2) + "\n", encoding="utf-8")
    print(f"{len(photos)} photos → {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
